apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-apk
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-apk  # The label should match the one in the pod template
  template:
    metadata:
      labels:
        app: flask-apk  # Adding the label here
    spec:
      containers:
        - name: flask-apk
          image: mdirshaq/flask-web-app:v2
          imagePullPolicy: Always
          ports:
            - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  type: LoadBalancer
  selector:
    app: flask-apk  # This should match the label in the Deployment
  ports:
    - port: 5000
      targetPort: 5000
